[build]
builder = "NIXPACKS"
buildCommand = "bun install"

[deploy]
startCommand = "bun start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10